version: 0.0
os: linux
files:
  - source: /
    destination: /opt/
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: .aws/scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: .aws/scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: .aws/scripts/stop_server.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: .aws/scripts/cleaning_install.sh
      timeout: 300
      runas: root
